menu:
- {name: 'research', url: '/research'}
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'news', url: '/news'}
- {name: 'courses', url: '/courses'}
- {name: 'resources', url: '/resources'}

researchers:
- {name: 'Shankari Rajagopal',
  title: 'Harold C. Early Physics Early Career Professor, Assistant Professor of Physics',
  pronouns: 'she/her',
  department: 'Physics',
  institution: 'University of Michigan',
  institution_address: '450 Church Street, Ann Arbor, MI 48109',
  phone: '(775) 225-7355',
  email: 'svraj [at] umich [dot] edu',
  office: 'Homer A. Neal Lab 4223',
  lab: 'Homer A. Neal Lab 3214' ,
  image: 'assets/img/RajagopalSV_photo_oregon.jpg',
  cv: 'assets/cvs/20250217__SVR_CV.pdf',
  about: 'Shankari Rajagopal is an atomic physics experimentalist interested in driven systems, measurement, and interactive quantum dynamics. From 2019-2024, she was a postdoctoral research scholar and <a href="https://stanfordsciencefellows.stanford.edu/">Stanford Science Fellow</a> at Stanford University in the group of <a href="https://sites.google.com/stanford.edu/sslab/">Monika Schleier-Smith</a>, working on improved coherence and uses of dressed Rydberg interactions in atomic tweezer arrays. She completed her graduate studies in 2019 at the University of California Santa Barbara in the lab of <a href="https://web.physics.ucsb.edu/~weld/">David Weld</a>, building two experiments in a new lab (lithium and strontium!) and then studying non-equilibrium dynamics with Bose-Einstein condensates in lattices. Shankari is particularly interested in applications of driven quantum systems and measurement feedback to quantum simulation, optimization, and metrology.<br><br> In her spare time, Shankari enjoys getting outdoors (long-distance running, hiking, biking, climbing, gardening), music (live shows, playing, and composing, the latter two very poorly), and <s>stealing</s> meeting as many dogs as possible.',
  url: 'shankari-rajagopal',
}

gs:
- {name: 'Liam Daly',
  title: 'Graduate Researcher',
  pronouns: 'he/him',
  department: 'Physics',
  institution: 'University of Michigan',
  institution_address: '450 Church Street, Ann Arbor, MI 48109',
  phone: '(775) 225-7355',
  email: 'liamdaly [at] umich [dot] edu',
  office: 'Homer A. Neal Lab',
  lab: 'Homer A. Neal Lab 3214' ,
  image: 'assets/img/LiamDaly-Website-Picture.jpg',
  about: 'Liam is a first year physics graduate student at the University of Michigan. He earned his B.S. in Physics from the University of North Texas in 2024, where he worked in the lab of Jens Neu on THz-Time Domain Spectroscopy. In 2023, he participated in the University of Michigan NSF REU program, working with the Goldman group on simulations of carrier concentration in submonolayer quantum dots. Outside the lab, Liam enjoys playing stringed instruments, hiking, kayaking, and both watching and learning how to play hockey.',
  url: 'liam-daly',
  website: 'https://www.linkedin.com/in/liamdaly100/',
}
- {name: 'Riva Jangra',
  title: 'Visiting Researcher',
  pronouns: 'she/her',
  department: 'Physics',
  institution: 'Dartmouth College, Perimeter Institute',
  institution_address: '6127 Wilder Laboratory Hanover, NH 03755-3528',
  phone: '7752257355',
  email: 'riva.jangra.GR [at] umich [dot] edu',
  office: 'Homer A. Neal Lab',
  lab: 'Homer A. Neal Lab 3214' ,
  image: 'assets/img/rivajangra.png',
  about: 'Riva is a visiting researcher from the Perimeter Institute who will begin her PhD in physics at Dartmouth College in Fall 2025. Over the past year she’s helped build the atomic-level compiler infrastructure for Professor Rajibul Islam’s trapped-ion quantum computer, explored AI applications in Celestial Holography with Professor Sabrina Pasterski, and most recently worked on topological graph theoretic applications for superconducting qubits with Professor Andrew Houck’s lab. She’s excited to dive into the guts of quantum control systems and is passionate about experimentally verifying theoretical work. If she’s not at the lab, you’ll find Riva at a pottery wheel, training Brazilian jiu-jitsu, devouring horror novels, or skiff sailing!',
  url: 'riva-jangra',
  website: 'https://www.linkedin.com/in/riva-jangra-36b83928b/?originalSubdomain=ca',
}

ug:
- {name: 'Hsu Ting Tung',
  title: 'Undergraduate Researcher',
  pronouns: 'he/him',
  major: 'Physics',
  minor: 'Computer Science',
  institution: 'University of Michigan',
  institution_address: '450 Church Street, Ann Arbor, MI 48109',
  phone: '(775) 225-7355',
  email: 'tunght [at] umich [dot] edu',
  lab: 'Homer A. Neal Lab 3214' ,
  image: 'assets/img/hsutingtung.jpg',
  about: 'Hsu Ting is a junior majoring in Physics and minoring in Computer Science at the University of Michigan, particularly interested in quantum computing and quantum information science. He is also passionate about gastronomy, and in his spare time, likes to try out new restaurants and cook food that doesn’t meet his expectations. He tries to balance his excess caloric intake with sports, having fenced professionally, and mainly training Muay Thai and playing tennis nowadays.',
  url: 'hsu-ting-tung',
}
- {name: 'Yiyi Zhu',
  title: 'Undergraduate Researcher',
  pronouns: 'he/him',
  major: 'Physics, Mathematics',
  minor: 'none',
  institution: 'University of Michigan',
  institution_address: '450 Church Street, Ann Arbor, MI 48109',
  phone: '(775) 225-7355',
  email: 'yiyizhu [at] umich [dot] edu',
  lab: 'Homer A. Neal Lab 3214' ,
  image: 'assets/img/yiyizhu_website.png',
  about: 'Yiyi is a junior undergraduate student at the University of Michigan, majoring in Physics and Mathematics. He joined the Rajagopal Lab in Spring 2025. Prior to that, he conducted research on the Gromov hyperbolicity of the fine arc graph in the University of Michigan Lab of Geometry and worked on improving methods for detecting continuous gravitational waves. Outside of academics, Yiyi enjoys rock climbing (still learning—and still falling), cycling, hiking, and playing the violin.',
  url: 'yiyi-zhu',
}
- {name: 'Jacob Lepley',
  title: 'Undergraduate Researcher',
  pronouns: 'he/him',
  major: 'ECE',
  minor: 'Physics',
  institution: 'University of Michigan',
  institution_address: '450 Church Street, Ann Arbor, MI 48109',
  phone: '(775) 225-7355',
  email: 'jnlepley [at] umich [dot] edu',
  lab: 'Homer A. Neal Lab 3214' ,
  image: 'assets/img/jacoblepley.jpg',
  about: 'I am senior studying computer engineering and physics, and it’s my goal to eventually work in quantum computing. In my spare time I enjoy working out and playing souls like and rogue like games. Given the opportunity, I love to travel, camp, build PCs, and hike. ',
  url: 'jacob-lepley',
}
#- {name: 'Lab Technician',
#  title: 'Researcher',
#  department: 'Physics & Astronomy',
#  institution: 'Some University',
#  institution_address: '1 Main Street, Canada',
#  phone: '(000) 000-0000',
#  email: 'hello@university.edu',
#  office: 'Science Building 505',
#  image: 'assets/img/lab-technician.jpg',
#  url: 'lab-technician',
#}
#- {name: 'Graduate Student',
#  title: 'Researcher',
#  department: 'Physics & Astronomy',
#  institution: 'Some University',
#  institution_address: '1 Main Street, Canada',
#  phone: '(000) 000-0000',
#  email: 'hello@university.edu',
#  office: 'Science Building 505',
#  image: 'assets/img/graduate-student.jpg',
#  url: 'graduate-student',
#}

courses:
- {term: "Winter 2025",
  name: 'PHYS106 Section 001 (Everyday Physics)',
  url: 'https://umich.instructure.com/courses/734169',
}

social:
- {icon: 'fab fa-github', link: 'https://github.com/rajagopallab'}
- {icon: 'fa fa-university', link: 'https://lsa.umich.edu/physics/people/faculty/shankari-rajagopal.html'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'linkedin', link: 'https://www.linkedin.com/in/shankari-rajagopal-3a520015'}

contacts:
- {name: 'Shankari Rajagopal',
  title: 'Assistant Professor',
  department: 'Physics',
  institution: 'University of Michigan',
  institution_address: '450 Church Street, Ann Arbor, MI 48109',
  phone: '(775) 225-7355',
  email: 'hello@university.edu',
  office: 'Homer A. Neal Lab 4223',
  image: 'assets/img/RajagopalSV_photo_oregon.jpg',
}
